### ISSUE TITLE
Update on CommonVoice

### ISSUE THREAD

**Issue by mthrok** [pytorch/audio#1077]
For master branch;

- [x] ~#1079~ Revert #1018
- [x] ~#1080~ Disallow `download=True` (cherry-pick ~#1076~)
- [x] #1082 Remove execution paths for `download=True` and clean up the code
- ~#1083~ Superseded by updated #1082 
    - ~Deprecate `download` and `url` argument~
    - ~Introduce `language` argument.~
    ~The introduction of `language` argument should come with the team's agreement.~
- ~Update the default version.~ Version parameter is deprecated and no longer used.
    ~This has to be a separate commit as this deserves a dedicated line in 0.8 release note.~

For release 0.7.1 branch;
- [x] ~#1075~ Revert #1065
- [x] ~#1076~ Disallow `download=True`
