### ISSUE TITLE
v0.9 release checklist

### ISSUE THREAD

**Issue by mthrok** [pytorch/audio#1527]
Note: This is not exhaustive list.
### Deprecation
- [x] #1535 Update deprecation warnings so that instead of saying "feature release", it says specific release version. [F.resample](https://github.com/pytorch/audio/blob/22fe802635d28b6ca5fdd15a66ac2cb871ad6881/torchaudio/functional/functional.py#L1316), [T.MelScale](https://github.com/pytorch/audio/blob/3bb3287f49e0a389bcf3860fc595a5bca7b39a10/torchaudio/transforms.py#L289)
- [x] #1533 Deprecate `torchaudio.compliance.kaldi.resample_waveform`. 
- [x] #1534 Remove deprecated arguments from [`CommonVoice`](https://github.com/pytorch/audio/blob/14dd917ec60fa69ce3f7c6e3f2eaf520e67928b5/torchaudio/datasets/commonvoice.py#L33-L47)
### Documentation
- [ ] Add autograd support to related functionals/transforms.
- [x] #1550 Overall documentation update. We need to review the documentation and fix rendering / update docstrings that are not easy to understand.
  - [x] Fix DeepSpeech link rendering https://pytorch.org/audio/master/models.html#deepspeech
  - [x] Sound file backend: `Note` of `info`[[code](https://github.com/pytorch/audio/blob/14dd917ec60fa69ce3f7c6e3f2eaf520e67928b5/torchaudio/backend/soundfile_backend.py#L91-L94), [render](https://pytorch.org/audio/master/backend.html#torchaudio.backend.soundfile_backend.info)], `load`[[code](https://github.com/pytorch/audio/blob/14dd917ec60fa69ce3f7c6e3f2eaf520e67928b5/torchaudio/backend/soundfile_backend.py#L165-L168), [render](https://pytorch.org/audio/master/backend.html#torchaudio.backend.soundfile_backend.load)] and [`save`](https://github.com/pytorch/audio/blob/14dd917ec60fa69ce3f7c6e3f2eaf520e67928b5/torchaudio/backend/soundfile_backend.py#L329-L331) function. 
  - [x] wav2vec2 model: Add function index to the category on the right side.

### Example
- [x] #1538 C++ speech recognition example
### Tutorial
- [x] https://github.com/pytorch/tutorials/pull/1566
    - [x]  Update tutorial about HTK support.
There are comments about limited HTK compatibility ([Mel Filter Bank](https://pytorch.org/tutorials/beginner/audio_preprocessing_tutorial.html#comparison-against-librosa) and [MelSpectrogram](https://pytorch.org/tutorials/beginner/audio_preprocessing_tutorial.html#id1)), but this was resolved in #593. We should update the tutorial. The source code is found [here](https://github.com/pytorch/tutorials/blob/master/beginner_source/audio_preprocessing_tutorial.py#L978-L979) and [here](https://github.com/pytorch/tutorials/blob/master/beginner_source/audio_preprocessing_tutorial.py#L1040-L1041).
    - [x] Add resampling tutorial (as outlined in #1487)

## Optional
- [ ] Resolve #1501 
- [x] Resolve #1477 @malfet 

@carolineechen @cpuhrsch @vincentqb

**Comment by mthrok** [comment]
@carolineechen I think `resample` is better suited under `Utility` category.

https://pytorch.org/audio/master/functional.html#resample
